"""
This type stub file was generated by pyright.
"""

from deep_translator.baidu import BaiduTranslator
from deep_translator.chatgpt import ChatGptTranslator
from deep_translator.deepl import DeeplTranslator
from deep_translator.detection import batch_detection, single_detection
from deep_translator.google import GoogleTranslator
from deep_translator.libre import LibreTranslator
from deep_translator.linguee import LingueeTranslator
from deep_translator.microsoft import MicrosoftTranslator
from deep_translator.mymemory import MyMemoryTranslator
from deep_translator.papago import PapagoTranslator
from deep_translator.pons import PonsTranslator
from deep_translator.qcri import QcriTranslator
from deep_translator.yandex import YandexTranslator

"""Top-level package for Deep Translator"""
__copyright__ = ...
__author__ = ...
__email__ = ...
__version__ = ...
__all__ = ["GoogleTranslator", "PonsTranslator", "LingueeTranslator", "MyMemoryTranslator", "YandexTranslator", "MicrosoftTranslator", "QcriTranslator", "DeeplTranslator", "LibreTranslator", "PapagoTranslator", "ChatGptTranslator", "BaiduTranslator", "single_detection", "batch_detection"]
