"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

"""
baidu translator API
"""
__copyright__ = ...
class BaiduTranslator(BaseTranslator):
    """
    class that wraps functions, which use the BaiduTranslator translator
    under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., appid: Optional[str] = ..., appkey: Optional[str] = ..., **kwargs) -> None:
        """
        @param appid: your baidu cloud api appid.
        Get one here: https://fanyi-api.baidu.com/choose
        @param appkey: your baidu cloud api appkey.
        @param source: source language
        @param target: target language
        """
        ...
    
    def translate(self, text: str, **kwargs) -> str:
        """
        @param text: text to translate
        @return: translated text
        """
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        @param batch: list of texts to translate
        @return: list of translations
        """
        ...
    


