"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

__copyright__ = ...
class ChatGptTranslator(BaseTranslator):
    """
    class that wraps functions, which use the DeeplTranslator translator
    under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., api_key: Optional[str] = ..., model: Optional[str] = ..., **kwargs) -> None:
        """
        @param api_key: your openai api key.
        @param source: source language
        @param target: target language
        """
        ...
    
    def translate(self, text: str, **kwargs) -> str:
        """
        @param text: text to translate
        @return: translated text
        """
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        @param batch: list of texts to translate
        @return: list of translations
        """
        ...
    


