"""
This type stub file was generated by pyright.
"""

import argparse
from typing import Optional

"""Console script for deep_translator."""
__copyright__ = ...
class CLI:
    translators_dict = ...
    translator = ...
    def __init__(self, custom_args: Optional[list] = ...) -> None:
        ...
    
    def translate(self) -> None:
        """
        function used to provide translations from the parsed terminal arguments
        @return: None
        """
        ...
    
    def get_supported_languages(self) -> None:
        """
        function used to return the languages supported by the translator service
        from the parsed terminal arguments
        @return: None
        """
        ...
    
    def parse_args(self) -> argparse.Namespace:
        """
        function responsible for parsing terminal arguments and provide
        them for further use in the translation process
        """
        ...
    
    def run(self) -> None:
        ...
    


