"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union

"""
language detection API
"""
__copyright__ = ...
config = ...
def get_request_body(text: Union[str, List[str]], api_key: str, *args, **kwargs): # -> Any:
    """
    send a request and return the response body parsed as dictionary

    @param text: target text that you want to detect its language
    @type text: str
    @type api_key: str
    @param api_key: your private API key

    """
    ...

def single_detection(text: str, api_key: Optional[str] = ..., detailed: bool = ..., *args, **kwargs): # -> Any | None:
    """
    function responsible for detecting the language from a text

    @param text: target text that you want to detect its language
    @type text: str
    @type api_key: str
    @param api_key: your private API key
    @param detailed: set to True if you want to get detailed
    information about the detection process
    """
    ...

def batch_detection(text_list: List[str], api_key: str, detailed: bool = ..., *args, **kwargs): # -> list[Any]:
    """
    function responsible for detecting the language from a text

    @param text_list: target batch that you want to detect its language
    @param api_key: your private API key
    @param detailed: set to True if you want to
    get detailed information about the detection process
    """
    ...

