"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from deep_translator.base import BaseTranslator

"""
linguee translator API
"""
__copyright__ = ...
class LingueeTranslator(BaseTranslator):
    """
    class that wraps functions, which use the linguee translator under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., proxies: Optional[dict] = ..., **kwargs) -> None:
        """
        @param source: source language to translate from
        @param target: target language to translate to
        """
        ...
    
    def translate(self, word: str, return_all: bool = ..., **kwargs) -> Union[str, List[str]]:
        """
        function that uses linguee to translate a word
        @param word: word to translate
        @type word: str
        @param return_all: set to True to return all synonym of the translated word
        @type return_all: bool
        @return: str: translated word
        """
        ...
    
    def translate_words(self, words: List[str], **kwargs) -> List[str]:
        """
        translate a batch of words together by providing them in a list
        @param words: list of words you want to translate
        @param kwargs: additional args
        @return: list of translated words
        """
        ...
    


