"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

__copyright__ = ...
class MicrosoftTranslator(BaseTranslator):
    """
    the class that wraps functions, which use the Microsoft translator under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., api_key: Optional[str] = ..., region: Optional[str] = ..., proxies: Optional[dict] = ..., **kwargs) -> None:
        """
        @params api_key and target are the required params
        @param api_key: your Microsoft API key
        @param region: your Microsoft Location
        """
        ...
    
    def translate(self, text: str, **kwargs) -> str:
        """
        function that uses microsoft translate to translate a text
        @param text: desired text to translate
        @return: str: translated text
        """
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        """
        translate from a file
        @param path: path to file
        @return: translated text
        """
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        translate a batch of texts
        @param batch: list of texts to translate
        @return: list of translations
        """
        ...
    


