"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from deep_translator.base import BaseTranslator

"""
mymemory translator API
"""
__copyright__ = ...
class MyMemoryTranslator(BaseTranslator):
    """
    class that uses the mymemory translator to translate texts
    """
    def __init__(self, source: str = ..., target: str = ..., proxies: Optional[dict] = ..., **kwargs) -> None:
        """
        @param source: source language to translate from
        @param target: target language to translate to
        """
        ...
    
    def translate(self, text: str, return_all: bool = ..., **kwargs) -> Union[str, List[str]]:
        """
        function that uses the mymemory translator to translate a text
        @param text: desired text to translate
        @type text: str
        @param return_all: set to True to return all synonym/similars of the translated text
        @return: str or list
        """
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        """
        translate directly from file
        @param path: path to the target file
        @type path: str
        @param kwargs: additional args
        @return: str
        """
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        translate a list of texts
        @param batch: list of texts you want to translate
        @return: list of translations
        """
        ...
    


