"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

"""
papago translator API
"""
__copyright__ = ...
class PapagoTranslator(BaseTranslator):
    """
    class that wraps functions, which use google translate under the hood to translate text(s)
    """
    def __init__(self, client_id: Optional[str] = ..., secret_key: Optional[str] = ..., source: str = ..., target: str = ..., **kwargs) -> None:
        """
        @param source: source language to translate from
        @param target: target language to translate to
        """
        ...
    
    def translate(self, text: str, **kwargs) -> str:
        """
        function that uses google translate to translate a text
        @param text: desired text to translate
        @return: str: translated text
        """
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        """
        translate directly from file
        @param path: path to the target file
        @type path: str
        @param kwargs: additional args
        @return: str
        """
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        translate a list of texts
        @param batch: list of texts you want to translate
        @return: list of translations
        """
        ...
    


