"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

__copyright__ = ...
class QcriTranslator(BaseTranslator):
    """
    class that wraps functions, which use the QRCI translator under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., api_key: Optional[str] = ..., **kwargs) -> None:
        """
        @param api_key: your qrci api key.
        Get one for free here https://mt.qcri.org/api/v1/ref
        """
        ...
    
    @property
    def languages(self): # -> list[Any] | dict[Any, Any]:
        ...
    
    def get_domains(self): # -> str | Response:
        ...
    
    @property
    def domains(self): # -> str | Response:
        ...
    
    def translate(self, text: str, **kwargs) -> str:
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        translate a batch of texts
        @domain: domain
        @param batch: list of texts to translate
        @return: list of translations
        """
        ...
    


