"""
This type stub file was generated by pyright.
"""

from typing import Optional

__copyright__ = ...
def is_empty(text: str) -> bool:
    ...

def request_failed(status_code: int) -> bool:
    """Check if a request has failed or not.
    A request is considered successfull if the status code is in the 2** range.

    Args:
        status_code (int): status code of the request

    Returns:
        bool: indicates request failure
    """
    ...

def is_input_valid(text: str, min_chars: int = ..., max_chars: Optional[int] = ...) -> bool:
    """
    validate the target text to translate
    @param min_chars: min characters
    @param max_chars: max characters
    @param text: text to translate
    @return: bool
    """
    ...

