"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from deep_translator.base import BaseTranslator

"""
Yandex translator API
"""
__copyright__ = ...
class YandexTranslator(BaseTranslator):
    """
    class that wraps functions, which use the yandex translator
    under the hood to translate word(s)
    """
    def __init__(self, source: str = ..., target: str = ..., api_key: Optional[str] = ..., **kwargs) -> None:
        """
        @param api_key: your yandex api key
        """
        ...
    
    @property
    def languages(self): # -> list[Any] | dict[Any, Any]:
        ...
    
    @property
    def dirs(self, proxies: Optional[dict] = ...): # -> Any:
        ...
    
    def detect(self, text: str, proxies: Optional[dict] = ...): # -> Any:
        ...
    
    def translate(self, text: str, proxies: Optional[dict] = ..., **kwargs) -> str:
        ...
    
    def translate_file(self, path: str, **kwargs) -> str:
        """
        translate from a file
        @param path: path to file
        @return: translated text
        """
        ...
    
    def translate_batch(self, batch: List[str], **kwargs) -> List[str]:
        """
        translate a batch of texts
        @param batch: list of texts to translate
        @return: list of translations
        """
        ...
    


