name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1.1.7
      - name: Check Dockerfile
        run: hadolint Dockerfile
      - name: Run tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q
