name: Generate Localized File

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run translation
        uses: mrf0rtuna4/Git-Markdown-AutoTranslator@master
        env:
          LANGS: 'ru, ar, uk, it, ja'
          FILES: 'README.md, https://github.com/mrf0rtuna4/mrf0rtuna4/blob/main/README.md'

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: translations_indev
          build_dir: 'dist'
        env:
          GITHUB_TOKEN: ${{ secrets.GTK }}
